name: Java CI with Maven

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch all history for all branches and tags
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests
        run: mvn test
        continue-on-error: true

      - name: Set up Git identity
        run: |
          git config user.email "m.daoud@esi-sba.dz"
          git config user.name "ryaddaoud21"

      - name: Check test results
        if: ${{ failure() }}
        run: echo "Tests failed!"

      - name: Create failure branch
        if: ${{ failure() }}
        run: |
            echo "Tests failed!"
            git checkout -b failure-branch-${{ github.run_id }}
            git push origin failure-branch-${{ github.run_id }}

      - name: Git reset
        if: ${{ failure() }}
        run: |
          git fetch --deepen=2
          git checkout dev
          git reset --soft HEAD~1
          git push --force origin dev

